
ALTER TABLE public.movies
  ADD COLUMN IF NOT EXISTS title_en TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS title_tg TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS title_fa TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_en TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_tg TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_fa TEXT DEFAULT '';

ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS name_en TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS name_tg TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS name_fa TEXT DEFAULT '';
